sudo: false
language: node_js
node_js:
  - "5"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - gulp build
  - gulp s3-deploy
  - gulp s3-rename
# safelist
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
